<a href="https://colab.research.google.com/github/george1969434/VK_Introduction_ML/blob/main/DZ1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.1

In [ ]:
import timeit
import random
import numpy as np
X=np.array([[1,0,1],[2,0,2],[3,0,3],[4,4,4]])
X100=np.random.randint(0,10,(100,100))
X1000=np.random.randint(0,10,(1000,1000))
X10000=np.random.randint(0,10,(10000,10000))
def foo(X):
  prod=1
  for i in np.diag(X):
    if (i!=0):
      prod*=i
  return prod
print("Answer:")
print(foo(X))
print("Time for demension 100:")
%timeit foo(X100)
print("Time for demension 1000:")
%timeit foo(X1000)
print("Time for demension 10000:")
%timeit foo(X10000)



Answer:
3
Time for demension 100:


<ipython-input-61-9867e401a2c2>:12: RuntimeWarning: overflow encountered in scalar multiply
  prod*=i


80.6 µs ± 24.6 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
Time for demension 1000:
213 µs ± 35 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
Time for demension 10000:
1.72 ms ± 413 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


1.2

In [ ]:
import timeit
import random
import numpy as np
X=np.array([[1,0,1],[2,0,2],[3,0,3],[4,4,4]])
def foo(X):
  a=np.diag(X)
  a=np.where(a!=0,a,1)
  return np.prod(a)
print("Answer:")
print(foo(X))
print("Time for demension 100:")
%timeit foo(X100)
print("Time for demension 1000:")
%timeit foo(X1000)
print("Time for demension 10000:")
%timeit foo(X10000)

Answer:
3
Time for demension 100:
13.1 µs ± 2.48 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)
Time for demension 1000:
19.1 µs ± 1.25 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
Time for demension 10000:
102 µs ± 12.9 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


1.3

In [ ]:
import timeit
import random
import numpy as np
X=np.array([[1,0,1],[2,0,2],[3,0,3],[4,4,4]])
def foo(X):
  arr=np.diag(X)
  return arr[(arr!=0)].prod()
print("Answer:")
print(foo(X))
print("Time for demension 100:")
%timeit foo(X100)
print("Time for demension 1000:")
%timeit foo(X1000)
print("Time for demension 10000:")
%timeit foo(X10000)

Answer:
3
Time for demension 100:
7.24 µs ± 91 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
Time for demension 1000:
15.8 µs ± 2.83 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)
Time for demension 10000:
102 µs ± 15.9 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Вывод: третий и второй вариант оказались быстрее первого, так как содержат встроенную оптимизированную функцию prod(). Кроме того, в первом варианте мы работаем с каждым значение вектора, что значительно замедляет работу при работе с большой размерностью матрицы.

2.1

In [ ]:
import timeit
import random
import numpy as np
def vec(size):
  X=np.random.randint(0,10,(size,size))
  i=np.random.randint(0,10,size)
  j=np.random.randint(0,10,size)
  lst=[]
  for k in range(0,len(i)):
    lst.append(X[i[k],j[k]])
  return lst

print("Answer:")
print(vec(10))
print("Time for demension 100:")
%timeit lst100=vec(100)
print("Time for demension 1000:")
%timeit lst1000=vec(1000)
print("Time for demension 10000:")
%timeit lst10000=vec(10000)


Answer:
[0, 5, 8, 3, 4, 5, 6, 1, 1, 1]
Time for demension 100:
238 µs ± 3.79 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
Time for demension 1000:
16.7 ms ± 1.89 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
Time for demension 10000:
1.73 s ± 136 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


2.2

2.3

In [ ]:
import timeit
import random
import numpy as np
def vec(size):
  X=np.random.randint(0,10,(size,size))
  i=np.random.randint(0,10,size)
  j=np.random.randint(0,10,size)
  lst=[];
  lst=X[i[0:len(i)],j[0:len(i)]]
  return lst

print("Answer:")
print(vec(10))
print("Time for demension 100:")
%timeit lst100=vec(100)
print("Time for demension 1000:")
%timeit lst1000=vec(1000)
print("Time for demension 10000:")
%timeit lst10000=vec(10000)

Answer:
[5 9 3 6 1 5 6 1 0 6]
Time for demension 100:
209 µs ± 18.8 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
Time for demension 1000:
16.5 ms ± 1.64 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
Time for demension 10000:
1.79 s ± 151 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Вывод: вариант с векторами оказался незначительно быстрее варианта с циклами

3.1

In [ ]:
import timeit
import numpy as np
x=np.array([1,2,2,4])
y=np.array([4,2,1,2])
x100=np.random.randint(0,10,100)
y100=np.random.randint(0,10,100)
x1000=np.random.randint(0,10,1000)
y1000=np.random.randint(0,10,1000)
x10000=np.random.randint(0,10,10000)
y10000=np.random.randint(0,10,10000)
def mult(x,y):
  if(str(np.sort(y))== str(np.sort(x))):
    flag=True
  else:
    flag=False
  return flag

print("Answer:")
print(mult(x,y))
print("Time for demension 100:")
%timeit mult(x100,y100)
print("Time for demension 1000:")
%timeit mult(x1000,y1000)
print("Time for demension 10000:")
%timeit mult(x10000,y10000)


Answer:
True
Time for demension 100:
402 µs ± 17.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
Time for demension 1000:
3.18 ms ± 75.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
Time for demension 10000:
835 µs ± 126 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


3.2

In [ ]:
import timeit
import numpy as np
x=np.array([1,2,2,4])
y=np.array([4,2,1,2])
x100=np.random.randint(0,10,100)
y100=np.random.randint(0,10,100)
x1000=np.random.randint(0,10,1000)
y1000=np.random.randint(0,10,1000)
x10000=np.random.randint(0,10,10000)
y10000=np.random.randint(0,10,10000)
def mult(x,y):
  lst1=np.sort(x)
  lst2=np.sort(y)
  for i in range(0,len(lst1)):
    if(lst1[i]!=lst2[i]):
      return False
  return True

print("Answer:")
print(mult(x,y))
print("Time for demension 100:")
%timeit mult(x100,y100)
print("Time for demension 1000:")
%timeit mult(x1000,y1000)
print("Time for demension 10000:")
%timeit mult(x10000,y10000)

Answer:
True
Time for demension 100:
6.99 µs ± 2.09 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)
Time for demension 1000:
95.3 µs ± 1.03 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
Time for demension 10000:
938 µs ± 164 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


3.3

In [ ]:
import timeit
import numpy as np
x=np.array([1,2,2,4])
y=np.array([4,2,1,2])
x100=np.random.randint(0,10,100)
y100=np.random.randint(0,10,100)
x1000=np.random.randint(0,10,1000)
y1000=np.random.randint(0,10,1000)
x10000=np.random.randint(0,10,10000)
y10000=np.random.randint(0,10,10000)
def mult(x,y):
  return np.array_equal(np.sort(x), np.sort(y))

print("Answer:")
print(mult(x,y))
print("Time for demension 100:")
%timeit mult(x100,y100)
print("Time for demension 1000:")
%timeit mult(x1000,y1000)
print("Time for demension 10000:")
%timeit mult(x10000,y10000)



Answer:
True
Time for demension 100:
7.68 µs ± 216 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
Time for demension 1000:
59 µs ± 11.4 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
Time for demension 10000:
619 µs ± 16.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Выводы: в среднем третий вариант оказался самым лучшим благодаря встроенной функции array_equal(). Вариант с циклом оказался лучше варианта со строками (первого) и для размерности 100 быстрее чем третий вариант, так как при наличии первого несовпадения выдает False, чего нету ни в первом варианте, ни в третьем

4.1

In [ ]:
import timeit
import random
import numpy as np
X100=np.random.randint(0,4,(100))
X1000=np.random.randint(0,4,(1000))
X10000=np.random.randint(0,4,(10000))
x=np.array([6,2,0,3,0,0,5,7,0])
def foo(x):
  ans=[]
  for i in range(0,len(x)-1):
    if x[i]==0:
      ans.append(x[i+1])
  return max(ans)
print("Answer:")
print(foo(x))
print("Time for demension 100:")
%timeit foo(X100)
print("Time for demension 1000:")
%timeit foo(X1000)
print("Time for demension 10000:")
%timeit foo(X10000)

Answer:
5
Time for demension 100:
22.9 µs ± 465 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
Time for demension 1000:
230 µs ± 5.59 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
Time for demension 10000:
2.27 ms ± 47.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


4.2

In [ ]:
import timeit
import random
import numpy as np
X100=np.random.randint(0,4,(100))
X1000=np.random.randint(0,4,(1000))
X10000=np.random.randint(0,4,(10000))
x=np.array([6,2,0,3,0,0,5,7,0])
def foo(x):
  return max(x[i] for i in range(1,len(x)) if x[i-1]==0)
print("Answer:")
print(foo(x))
print("Time for demension 100:")
%timeit foo(X100)
print("Time for demension 1000:")
%timeit foo(X1000)
print("Time for demension 10000:")
%timeit foo(X10000)

Answer:
5
Time for demension 100:
23.6 µs ± 724 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
Time for demension 1000:
404 µs ± 103 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
Time for demension 10000:
2.46 ms ± 69.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


4.3

In [ ]:
import timeit
import random
import numpy as np
X100=np.random.randint(0,4,(100))
X1000=np.random.randint(0,4,(1000))
X10000=np.random.randint(0,4,(10000))
x=np.array([6,2,0,3,0,0,5,7,0])
def foo(x):
  isnull=x==0
  #print(isnull[:-1])
  return max(x[1:][isnull[0:len(x)-1]])
print("Answer:")
print(foo(x))
print("Time for demension 100:")
%timeit foo(X100)
print("Time for demension 1000:")
%timeit foo(X1000)
print("Time for demension 10000:")
%timeit foo(X10000)

Answer:
5
Time for demension 100:
7.72 µs ± 2.07 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)
Time for demension 1000:
26.7 µs ± 471 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
Time for demension 10000:
242 µs ± 3.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Выводы: самым быстрым оказался вариант с векторами, два других, с циклами показали примерно одинаковое время

5.1

In [ ]:
import timeit
import random
import numpy as np
pic=np.random.randint(0,10,(3,3,3))
numChannels=np.array([0.299,0.587,0.114])
pic100=np.random.randint(0,10,(100,100,100))
pic1000=np.random.randint(0,10,(1000,1000,1000))
num100=np.random.randint(0,10,100)
num1000=np.random.randint(0,10,1000)
def foo(pic,num):
  return np.round(np.dot(pic,num))
print("Answer:")
print(foo(pic,numChannels))
print("Time for demension 100:")
%timeit foo(pic100,num100)
print("Time for demension 1000:")
%timeit foo(pic1000,num1000)

Answer:
[[5. 8. 6.]
 [6. 2. 1.]
 [3. 6. 2.]]
Time for demension 100:
1.09 ms ± 12.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
Time for demension 1000:
1.29 s ± 218 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


5.2

In [ ]:
import timeit
import random
import numpy as np
pic=np.random.randint(0,10,(3,3,3))
numChannels=np.array([0.299,0.587,0.114])
pic100=np.random.randint(0,10,(100,100,100))
pic1000=np.random.randint(0,10,(1000,1000,1000))
num100=np.random.randint(0,10,100)
num1000=np.random.randint(0,10,1000)
def foo(pic,num):
  ans=np.zeros((len(pic),len(pic)))
  for i in range(len(pic)):
    for j in range(len(pic)):
      for k in range(len(pic)):
        ans[i][j]+=pic[i][j][k]*num[k]
  return np.round(ans)

  return np.dot(pic,num)
print("Answer:")
print(foo(pic,numChannels))
print("Time for demension 100:")
%timeit foo(pic100,num100)
print("Time for demension 1000:")
%timeit foo(pic1000,num1000)

Answer:
[[2. 6. 7.]
 [7. 2. 4.]
 [8. 7. 6.]]
Time for demension 100:
1.11 s ± 306 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
Time for demension 1000:


Выводы: сами вычисления в этой задачи довольно долгие, какой вариант не выбери, поэтому пришлось отбросить размерность 10000. Вариант со встроенной функцией dot(), как и ожидалось, оказался быстрее, чем вариант с циклами

6.1

In [7]:
import timeit
import random
import numpy as np
x=np.array([2,2,2,3,3,3,5,2,2])
X100=np.random.randint(0,4,(100))
X1000=np.random.randint(0,4,(1000))
X10000=np.random.randint(0,4,(10000))
def foo(x):
  lst=[x[0]]
  kol=[1]
  temp=x[0]
  for i in range(1,len(x)):
    if x[i]!=temp:
      lst.append(x[i])
      kol.append(1)
      temp=x[i]
    else:
      kol[len(kol)-1]+=1
  return lst,kol
print("Answer:")
print(foo(x))
print("Time for demension 100:")
%timeit foo(X100)
print("Time for demension 1000:")
%timeit foo(X1000)
print("Time for demension 10000:")
%timeit foo(X10000)

Answer:
([2, 3, 5, 2], [3, 3, 1, 2])
Time for demension 100:
45.2 µs ± 11.6 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
Time for demension 1000:
417 µs ± 11 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
Time for demension 10000:
4.26 ms ± 119 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


6.2

In [2]:
import timeit
import random
import numpy as np
x=np.array([2,2,2,3,3,3,5,2,2])
X100=np.random.randint(0,4,(100))
X1000=np.random.randint(0,4,(1000))
X10000=np.random.randint(0,4,(10000))
def foo(x):
  lst=[]
  kol=[]
  temp='-1'
  for s in str(x).replace(' ','').replace('[','').replace(']',''):
    if s!=temp:
      lst.append(s)
      kol.append(1)
      temp=s
    else:
      kol[len(kol)-1]+=1
  return lst,kol
print("Answer:")
print(foo(x))
print("Time for demension 100:")
%timeit foo(X100)
print("Time for demension 1000:")
%timeit foo(X1000)
print("Time for demension 10000:")
%timeit foo(X10000)

Answer:
(['2', '3', '5', '2'], [3, 3, 1, 2])
Time for demension 100:
485 µs ± 238 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
Time for demension 1000:
3.63 ms ± 360 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
Time for demension 10000:
76.6 µs ± 8.09 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


6.3

In [73]:
import timeit
import random
import numpy as np
x=np.array([2,2,2,3,3,3,5,2,2])
X100=np.random.randint(0,4,(100))
X1000=np.random.randint(0,4,(1000))
X10000=np.random.randint(0,4,(10000))
def foo(x):
  ind=np.where(x[:-1]!=x[1:])[0]
  ind=list(map(lambda k:k+1,ind))
  parts=np.split(x,ind)
  lst=[]
  kol=[]
  for i in parts:
    lst.append(i[0])
    kol.append(len(i))
  return lst,kol
print("Answer:")
print(foo(x))
print("Time for demension 100:")
%timeit foo(X100)
print("Time for demension 1000:")
%timeit foo(X1000)
print("Time for demension 10000:")
%timeit foo(X10000)


Answer:
([2, 3, 5, 2], [3, 3, 1, 2])
Time for demension 100:
156 µs ± 36.7 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
Time for demension 1000:
1.39 ms ± 303 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
Time for demension 10000:
14.2 ms ± 3.12 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


Выводы: в последней версии не смог совсем обойтись без циклов, поэтому этот вариант оказался не самым быстрым. Быстрее всего первый вариант с циклами, медленее всего - вариант со строками